### ISSUE TITLE
ItemManager API增加给予数量

### ISSUE THREAD

**Issue by MySoulcutting** [ankhorg/NeigeItems-Kotlin#10]
ItemManager.INSTANCE.getItemStack();
API可以指定基于的数量
例如:
给予50个物品
ItemManager.INSTANCE.getItemStack("物品",50);

**Comment by Neige7** [comment]
你应该意识到一件事，ni生成的是随机物品，单纯的设置物品数量往往是没有意义的。你过你在使用过程中有相关需要，可以自己书写相关方法，我对添加这条方法没有兴趣
