### ISSUE TITLE
比较奇怪的bug，

### ISSUE THREAD

**Issue by DreamMiu** [ankhorg/NeigeItems-Kotlin#11]
一共安装这几个NeigeItems、EasyItem、NeigeItemTag，在爆破掉落物快速捡起会有概率导致物品一个一个的分开情况，禁用这3个插件就不会出现，看下面图片，后台无报错
![image](https://github.com/ankhorg/NeigeItems-Kotlin/assets/30835281/7b1c5c70-e49b-475f-b583-8a5e37edae9f)
使用的eco附魔的稿子
![image](https://github.com/ankhorg/NeigeItems-Kotlin/assets/30835281/5d7c07a2-b7a6-409e-a7c9-e6006d722d58)

**Comment by DreamMiu** [comment]
图片是模拟的，不是实质情况相似

**Comment by Neige7** [comment]
打包压缩一个可以复现情况的测试端，加群私发给我，我看一下
QQ群648142579
