### ISSUE TITLE
MythicMobs 5.6.0 (snapshot) compatability

### ISSUE THREAD

**Issue by mappleaf** [ankhorg/NeigeItems-Kotlin#13]
Is there any plans to be added? Latest implemented 5.1.0 version is a bit (1.5 years) outdated and doesn't work in current version of NI (skills aren't usable and etc related to it and drops at the moment of writing)

**Comment by Neige7** [comment]
Does MythicMobs version 5.5.1 work correctly?

**Comment by Neige7** [comment]
use 1.16.21
