### ISSUE TITLE
Non-China wiki access

### ISSUE THREAD

**Issue by mappleaf** [ankhorg/NeigeItems-Kotlin#14]
As I said. No one outside China can access the wiki page, we doesn't have a QQ. Gumroad maybe? Or any another service?

**Comment by Neige7** [comment]
The plugin's wiki has been converted to a paid subscription model, priced at 99 RMB for permanent access (approximately 14 USD). The wiki is now hosted on Yuque (www.yuque.com) and is available only in Chinese. Therefore, it is indeed difficult for non-Chinese users to purchase and access the wiki for this plugin. The plugin is now primarily targeted at Chinese users, and non-Chinese users can only understand the usage of the plugin by reading the source code.

**Comment by Neige7** [comment]
But I have already written many examples in the default configuration. After translating them into other languages ​​using a translation engine, you should be able to understand the basic usage of the plugin to some extent.
