### ISSUE TITLE
Oraxen glyphs support in name/lore

### ISSUE THREAD

**Issue by mappleaf** [ankhorg/NeigeItems-Kotlin#15]
https://docs.oraxen.com/configuration/glyphs

**Comment by Neige7** [comment]
Why don't you just use the corresponding PlaceholderAPI variables provided by Oraxen?

**Comment by mappleaf** [comment]
> Why don't you just use the corresponding PlaceholderAPI variables provided by Oraxen?

Because of shift glyphs, for example, which used like <shift:-211>. It's isn't provided with placeholders as I know

**Comment by Neige7** [comment]
> > Why don't you just use the corresponding PlaceholderAPI variables provided by Oraxen?
> 
> Because of shift glyphs, for example, which used like shift:-211. It's isn't provided with placeholders as I know

i dont want to support that
