### ISSUE TITLE
1.21.1paper端，物品描述文字用不了rgb颜色

### ISSUE THREAD

**Issue by Greensxfl** [ankhorg/NeigeItems-Kotlin#21]
1.21.1paper端，用不了rgb颜色
物品的名字或者lore使用rgb颜色后，游戏里get到的物品文字颜色为rgb颜色代码最后一个字符的颜色
![QQ截图20241120212655](https://github.com/user-attachments/assets/271e5ca6-5845-4c99-8514-09c10a451dbf)
![QQ截图20241120212742](https://github.com/user-attachments/assets/49c59f37-d45c-4e5a-a442-4e373ca42af5)
![QQ截图20241120212803](https://github.com/user-attachments/assets/0c73ae34-31b3-4f6d-a06d-10eeb7a04091)
![QQ截图20241120212814](https://github.com/user-attachments/assets/fab9b8df-1288-4d9c-88a8-9196e8a8d439)

**Comment by Neige7** [comment]
NeigeItems在1.21.1部分功能残废是已知问题，修复优先级不会太高，可能会在未来几周内修复。

**Comment by Neige7** [comment]
1.20.49版本已修复
