### ISSUE TITLE
最新版不支持jdk19吗

### ISSUE THREAD

**Issue by xiaojinxs69** [ankhorg/NeigeItems-Kotlin#22]
最新版不支持jdk19吗

**Comment by Neige7** [comment]
jdk21测试一切正常

**Comment by xiaojinxs69** [comment]
[12:29:28 ERROR]: Fatal error trying to convert NeigeItems v1.20.43:pers/neige/neigeitems/item/builder/NewItemBuilder.class
java.lang.IllegalArgumentException: Unsupported class file major version 65只能用21吗？

**Comment by xiaojinxs69** [comment]
当前用的jdk19.0.2

**Comment by Neige7** [comment]
> [12:29:28 ERROR]: Fatal error trying to convert NeigeItems v1.20.43:pers/neige/neigeitems/item/builder/NewItemBuilder.class java.lang.IllegalArgumentException: Unsupported class file major version 65只能用21吗？

1.21下NI只支持java21+
