### ISSUE TITLE
1.21.1 lefa的端 进入疯狂报错

### ISSUE THREAD

**Issue by fyxrim** [ankhorg/NeigeItems-Kotlin#23]
![image](https://github.com/user-attachments/assets/95c90a7e-46f5-4022-bc98-78db439a11d9)
![image](https://github.com/user-attachments/assets/aaa6c4cc-8ffa-40e4-b8db-8960cd9f4d33)

**Comment by Neige7** [comment]
最新版NI不支持1.21.1，对于1.20.5+的版本，只支持1.21.3

**Comment by fyxrim** [comment]
那个版本可以用1.21.1？

**Comment by Neige7** [comment]
> 那个版本可以用1.21.1？

自行测试
